### ISSUE TITLE
x86_pkg temperature (CPU?)

### ISSUE THREAD

**Issue by dflvunoooooo** [roger-/hass-sysmon#7]
Just for clarification, is the x86_pkg temperature the average temperature of the CPU? I didn't understand what the script is calling to get its information, I am sorry.

**Comment by roger-** [comment]
That information comes from the kernel and isn't standardized so you have to look up your specific cpu/motherboard interpretation.

**Comment by dflvunoooooo** [comment]
I see, thank you.
